### PR TITLE
HBASE-27935 Introduce Jenkins PR job for hbase-kustomize (addendum)

### PR DESCRIPTION
**Pull request by ndimiduk**
Add executable permissions to the shell scripts.

### CODE REVIEW

**Comment by ndimiduk** [comment]
PR build fails with

```
[2023-06-16T09:13:50.928Z] [INFO] Launching Yetus via /home/jenkins/jenkins-home/workspace/hbase-kustomize-github-pr_PR-3/yetus-precommit-check/src/dev-support/jenkins/jenkins_precommit_github_yetus.sh
[2023-06-16T09:13:50.928Z] /home/jenkins/jenkins-home/workspace/hbase-kustomize-github-pr_PR-3/yetus-precommit-check@tmp/durable-10c0e8a4/script.sh: line 4: /home/jenkins/jenkins-home/workspace/hbase-kustomize-github-pr_PR-3/yetus-precommit-check/src/dev-support/jenkins/jenkins_precommit_github_yetus.sh: Permission denied
script returned exit code 126
```

**Comment by ndimiduk** [comment]
PR build fails with:

```
[2023-06-16T09:24:09.010Z] Starting docker build...
[2023-06-16T09:24:09.010Z] ERROR: BuildKit is enabled but the buildx component is missing or broken.
[2023-06-16T09:24:09.010Z]        Install the buildx component to build images with BuildKit:
[2023-06-16T09:24:09.010Z]        https://docs.docker.com/go/buildx/
```

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   3m  7s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ main Compile Tests _ |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  codespell  |   0m  1s |  |  No new issues.  |
| +1 :green_heart: |  detsecrets  |   0m  2s |  |  The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  hadolint  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  shelldocs  |   0m  0s |  |  No new issues.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m  0s |  |  The patch does not generate ASF License warnings.  |
|  |   |   3m 16s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 |
| GITHUB PR | https://github.com/apache/hbase-kustomize/pull/4 |
| Optional Tests | dupname asflicense codespell detsecrets hadolint shellcheck shelldocs |
| uname | Linux ec7400b475a6 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | nobuild |
| Personality | /home/jenkins/jenkins-home/workspace/hbase-kustomize-github-pr_PR-4/yetus-precommit-check/src/.yetus/personality.sh |
| git revision | main / 843e2bace2951a4743e1f5b4a320ace7cd48a3b3 |
| Max. process+thread count | 10 (vs. ulimit of 5000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/hbase-kustomize-github-pr/job/PR-4/8/console |
| versions | git=2.25.1 hadolint=2.10.0 codespell=2.2.1 detsecrets=1.2.0 shellcheck=0.8.0 |
| Powered by | Apache Yetus 0.14.1 https://yetus.apache.org |


This message was automatically generated.

**Review by busbey — APPROVED** [review]

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   3m 14s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ main Compile Tests _ |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  codespell  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  detsecrets  |   0m  1s |  |  The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  hadolint  |   0m  1s |  |  No new issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  shelldocs  |   0m  1s |  |  No new issues.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m  0s |  |  The patch does not generate ASF License warnings.  |
|  |   |   3m 22s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 |
| GITHUB PR | https://github.com/apache/hbase-kustomize/pull/4 |
| Optional Tests | dupname asflicense codespell detsecrets hadolint shellcheck shelldocs |
| uname | Linux 12f64f2fa70f 5.4.0-1101-aws #109~18.04.1-Ubuntu SMP Mon Apr 24 20:40:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | nobuild |
| Personality | /home/jenkins/jenkins-home/workspace/hbase-kustomize-github-pr_PR-4/yetus-precommit-check/src/.yetus/personality.sh |
| git revision | main / ae11ed7a0e8f5fa6bbecf6ece2d848ebc0e83429 |
| Max. process+thread count | 8 (vs. ulimit of 5000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/hbase-kustomize-github-pr/job/PR-4/9/console |
| versions | git=2.25.1 hadolint=2.10.0 codespell=2.2.1 detsecrets=1.2.0 shellcheck=0.8.0 |
| Powered by | Apache Yetus 0.14.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 26s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ main Compile Tests _ |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  codespell  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  detsecrets  |   0m  1s |  |  The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  hadolint  |   0m  1s |  |  No new issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  shelldocs  |   0m  1s |  |  No new issues.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m  0s |  |  The patch does not generate ASF License warnings.  |
|  |   |   0m 35s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 |
| GITHUB PR | https://github.com/apache/hbase-kustomize/pull/4 |
| Optional Tests | dupname asflicense codespell detsecrets hadolint shellcheck shelldocs |
| uname | Linux c783bf341b49 5.4.0-1101-aws #109~18.04.1-Ubuntu SMP Mon Apr 24 20:40:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | nobuild |
| Personality | /home/jenkins/jenkins-home/workspace/hbase-kustomize-github-pr_PR-4/yetus-precommit-check/src/.yetus/personality.sh |
| git revision | main / ae11ed7a0e8f5fa6bbecf6ece2d848ebc0e83429 |
| Max. process+thread count | 9 (vs. ulimit of 5000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/hbase-kustomize-github-pr/job/PR-4/10/console |
| versions | git=2.25.1 hadolint=2.10.0 codespell=2.2.1 detsecrets=1.2.0 shellcheck=0.8.0 |
| Powered by | Apache Yetus 0.14.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
Thanks @busbey .

**Pull request merged**
